/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-11 00:05:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>おみくじ課題</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("</head>\n");
      out.write("<body style=\"background-image:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${backgroundImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <section class=\"omikuji\">\n");
      out.write("      <h1>今日の運勢を占ってみよう！</h1>\n");
      out.write("      <h3 id='timeZone'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seasonMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("      <button class=\"change\" onclick=\"pushChangeBtn()\">時間帯を変える</button>\n");
      out.write("      <img src=\"images/omikuji-torii.png\">\n");
      out.write("      <form method=\"post\" action=\"omikuji\" id=\"pushBtn\">\n");
      out.write("        <input type=\"submit\" value=\"引く\">\n");
      out.write("        <input type=\"hidden\" name=\"mode\" value=\"draw\">\n");
      out.write("      </form>\n");
      out.write("      <form method=\"post\" action=\"omikuji\" id=\"pushBtn\">\n");
      out.write("        <input type=\"submit\" value=\"確率\">\n");
      out.write("        <input type=\"hidden\" name=\"mode\" value=\"prob\">\n");
      out.write("      </form>\n");
      out.write("      <button onclick=\"pushHistoryBtn()\">履歴</button>\n");
      out.write("    </section>\n");
      out.write("    <form method=\"post\" action=\"edit\" id=\"pushBtn\">\n");
      out.write("      <input type=\"submit\" value=\"おみくじ管理画面\">\n");
      out.write("      <input type=\"hidden\" name=\"mode\" value=\"link\">\n");
      out.write("    </form>\n");
      out.write("    <section id=\"result\">\n");
      out.write("      <div id='result_container'>\n");
      out.write("        <h1 id=\"fortune\"></h1>\n");
      out.write("        <h2 id=\"word\"></h2>\n");
      out.write("        <div><img src=\"\" id= \"result_img\"></div>\n");
      out.write("        <button class=\"backOne\" onclick=\"pushBackBtn()\">戻る</button>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"history\">\n");
      out.write("     <div id=\"history_container\">\n");
      out.write("      <h2>過去10回の履歴(上から最新結果)</h2>\n");
      out.write("      <ul id='historyList'></ul>\n");
      out.write("      <button class=\"backTwo\" onclick=\"pushBackBtn()\">戻る</button>\n");
      out.write("     </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"probability\" class=\"hidden\">\n");
      out.write("     <div id=\"probability_container\">\n");
      out.write("        <h2>おみくじの種類と時間帯別の確率一覧</h2>\n");
      out.write("        <table border=\"1\">\n");
      out.write("          <tr>\n");
      out.write("            <th></th><th>大吉</th><th>吉</th><th>凶</th><th>大凶</th>\n");
      out.write("          </tr>\n");
      out.write("          <tr id=\"probTable\">\n");
      out.write("            <th></th><td></td><td></td><td></td><td></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("        <button class=\"backThree\" onclick=\"pushBackBtn()\">戻る</button>\n");
      out.write("     </div>\n");
      out.write("    </section>\n");
      out.write("    <section id=\"clock\">\n");
      out.write("      <div id=\"clock_container\">\n");
      out.write("        <h3>時間帯を変更する</h3>\n");
      out.write("        <ul class=\"kujiHenkou\">\n");
      out.write("          <li>\n");
      out.write("            <form method=\"post\" action=\"omikuji\">\n");
      out.write("              <input type=\"submit\" value=\"朝\">\n");
      out.write("              <input type=\"hidden\" name=\"hour\" value=\"7\" class=\"opa\">\n");
      out.write("              <input type=\"hidden\" name=\"mode\" value=\"time\">\n");
      out.write("            </form>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <form method=\"post\" action=\"omikuji\">\n");
      out.write("              <input  type=\"submit\" value=\"昼\">\n");
      out.write("              <input type=\"hidden\" name=\"hour\" value=\"12\" class=\"opa\">\n");
      out.write("              <input type=\"hidden\" name=\"mode\" value=\"time\">\n");
      out.write("            </form>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <form method=\"post\" action=\"omikuji\">\n");
      out.write("              <input type=\"submit\" value=\"夜\">\n");
      out.write("              <input type=\"hidden\" name=\"hour\" value=\"18\" class=\"opa\">\n");
      out.write("              <input type=\"hidden\" name=\"mode\" value=\"time\">\n");
      out.write("            </form>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <form method=\"post\" action=\"omikuji\">\n");
      out.write("              <input type=\"submit\" value=\"夕方\">\n");
      out.write("              <input type=\"hidden\" name=\"hour\" value=\"20\" class=\"opa\">\n");
      out.write("              <input type=\"hidden\" name=\"mode\" value=\"time\">\n");
      out.write("            </form>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <button class=\"backfour\" onclick=\"pushBackBtn()\">戻る</button>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"overlay\"></div>\n");
      out.write("  <script>\n");
      out.write("    const fortuneResult = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    const fortuneText = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    const fortuneImg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\n");
      out.write("    const probs0 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${probs0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    const probs1 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${probs1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"%\";\n");
      out.write("    const probs2 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${probs2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"%\";\n");
      out.write("    const probs3 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${probs3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"%\";\n");
      out.write("    const probs4 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${probs4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"%\";\n");
      out.write("\n");
      out.write("    const historyStr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${historyList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    const historyArray = historyStr.slice(1).slice(0, -1).split(',');\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("  <script src=\"main.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
